### ISSUE TITLE
Error 127 while making bash

### ISSUE THREAD

**Issue by Yijia-Chen** [mohit1997/DNA_Compression#1]
I ran the following to set up the environment:

    cd docker
    make bash BACKEND=tensorflow GPU=0 DATA=/path/to/data/

After completing the last step out of 18, I got this:

    Step 18/18 : CMD jupyter notebook --port=8888 --ip=0.0.0.0
     ---> Using cache
     ---> 0a5b71530fd3
    Successfully built 0a5b71530fd3
    Successfully tagged keras:latest
    usage: dirname path
    GPU=0 nvidia-docker run -it -v :/src/workspace -v /path/to/data/:/data --env KERAS_BACKEND=tensorflow keras bash
    /bin/sh: nvidia-docker: command not found
    make: *** [bash] Error 127

Is this because my system is macOS, or do I need to change some directory?

**Comment by kedartatwawadi** [comment]
Hi Yijia,

As of now, we use CuDNNLSTM/CuDNNGRU in our models. So, GPU and nvidia-docker are necessary to run the code (have updated the Readme accordingly). 

macOS might not be able to run the code due to this issue. We will work on providing a non-GPU based branch soon.

**Comment by kedartatwawadi** [comment]
I have created a branch [noGPU](https://github.com/mohit1997/DeepZip/tree/noGPU) for running on a CPU. The code has been tested on macOS Mojave. But, please comment if you face issues!

**Comment by Yijia-Chen** [comment]
Now I have this:

    Successfully built 70c8f941b9d1
    Successfully tagged keras:latest
    usage: dirname path
    docker run -it -v :/src/workspace -v /path/to/data/:/data --env KERAS_BACKEND=tensorflow keras bash
    docker: Error response from daemon: Mounts denied:
    The path /path/to/data/
    is not shared from OS X and is not known to Docker.
    You can configure shared paths from Docker -> Preferences... -> File Sharing.
    See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
    .
    make: *** [bash] Error 125

How may I fix this? I can't seem to add `/path/to/data` directly to docker's File Sharing directories.

**Comment by kedartatwawadi** [comment]
Hi Yijia,

/path/to/data is the path to the DeepZip directory on your machine. 
For example in my case it is: `/Users/kedar/code/DeepZip`

**Comment by Yijia-Chen** [comment]
Thanks! It now works on my macOS High Sierra without problems.
