### ISSUE TITLE
can this project compress bytes?

### ISSUE THREAD

**Issue by JsBlueCat** [mohit1997/DNA_Compression#10]
[test.zip](https://github.com/mohit1997/DeepZip/files/4364654/test.zip)

i have bytes data which saved in 16 HEX format.
can deepzip compress this file ? 

the code can't compress the test file
pleese unzip test.zip file

**Comment by mohit1997** [comment]
You can go to DeepZip/data/parse_new.py
and edit line 15-16
```python
with open(args.input_file_path, 'rb') as fp:
    data = fp.read()
```

Let me know if there are any issues.

**Comment by mohit1997** [comment]
I have updated the code, please try again.
