### ISSUE TITLE
About the lack of documents

### ISSUE THREAD

**Issue by Yoniming** [mohit1997/DNA_Compression#13]
Dear sir,
Hello,I follow the steps to test，but due to the lack of files of "data/compressed/xor20/biLSTM.reconstructed.txt",i can not go on,where can I find this file？Can you answer my problem? thank you

**Comment by mohit1997** [comment]
This file would be generated after you compress xor20.txt. Can you specify which step are you precisely stuck at? Were you able to install all the dependencies and parse the files needed to be compressed?

**Comment by Yoniming** [comment]
Thank you for your reply! First of all, I installed the required package for the experiment, while running. / run_ parser.sh,I found the folder "files_ to_ be_ compressed" is missing, so I created it and put the test file "xor20.txt" in it, and then run. / run_ experiments.sh,the problem is missing documents "biLSTM.reconstructed.txt" , what's the problem with my operation steps? Thank you for your reply!

**Comment by mohit1997** [comment]
Can you upload the terminal output of the last command “./run_ experiments.sh“ here?

**Comment by Yoniming** [comment]
This is the output:








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mohit Goyal"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 晚上8:42
收件人:&nbsp;"mohit1997/DeepZip"<DeepZip@noreply.github.com&gt;;
抄送:&nbsp;"龙LOVE凤"<771708451@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mohit1997/DeepZip] About the lack of documents (#13)





 
Can you upload the terminal output of the last command “./run_ experiments.sh“ here?

**Comment by mohit1997** [comment]
Can you upload the output log again? I received an email regarding your comment but it probably got deleted.

**Comment by Yoniming** [comment]
Because I couldn't upload the picture, I provided the wrong code information:

(tf) server109@server109:~/MMM/DeepZip-master/data$ ./run_parser.sh

filename: files_to_be_compressed/xor20.txt
xor20
10000000
{97: 0, 98: 1}
{0: 97, 1: 98}
[[0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]
b'abbaaababb'
- - - - - 

(tf) ubuntu@ubuntu:~/MMM/LSTM-compression/DeepZip-master/src$ ./run_experiments.sh biLSTM GPUID

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: tqdm in /home/ubuntu/MMM/LSTM-compression/DeepZip-master/tf/lib/python3.6/site-packages (4.46.0)
../data/processed_files/xor20.npy
xor20
../data/processed_files/xor20.param.json
cmp: ../data/compressed/xor20/biLSTM.reconstructed.txt: No such file or directory
2
cmp: ../data/compressed/xor20/biLSTM.reconstructed.txt: No such file or directory
continuing
Starting training ...
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/ubuntu/MMM/LSTM-compression/DeepZip-master/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ubuntu/MMM/LSTM-compression/DeepZip-master/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ubuntu/MMM/LSTM-compression/DeepZip-master/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

**Comment by mohit1997** [comment]
h, thanks for posting the log. `ImportError: libcublas.so.9.0` this error is the culprit behind your problem. You need to ensure that Cuda and CuDNN are installed in your system. If you don't have GPU please use the `nogpu` branch. Seeing from your issue, I think once you take care of this, you should be able to use this method. Note that you need Cuda 9.0 for this library to work with GPU.

**Comment by Yoniming** [comment]
Can only CUDA 9.0 be completed? I used CUDA 10.1 and 8.0, and I downloaded the version of tensorflow they needed, but I encountered the same error.

**Comment by mohit1997** [comment]
Can you execute the following python code to see if TensorFlow detects your GPU or not?
```python
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```
Also which version of tensorflow are you using? You need TensorFlow 1.13 and Keras 2.2.2. It might work with other Tensorflow 1.xx versions but not with tensorflow 2.x.

**Comment by Yoniming** [comment]
Yes, tensorflow can detect my GPU. I think CUDA 10.0 with tensorflow 1.13 is OK. But one of my CUDA is 10.1, so I can only choose tenserflow 2.0 or above. So I chose CUDA 8.0 and found tensorflow 1.3 corresponding to it, which is why I didn't choose tensorflow 1.13.

**Comment by mohit1997** [comment]
Can you try installing TensorFlow-GPU 1.3 and Keras 2.0.6? Then try running the code, let me know if it doesn't work. Another option is to use docker installation which will take care of the Cuda version.

**Comment by Yoniming** [comment]
Hello, keras 2.0.6 doesn't look suitable because there will be an error of importerror: cannot import name "cudnnlstm". I think this version is too low. In addition, there will be errors when using docker for installation. I see the prompt cuda9.0, and I have not continued the installation.

**Comment by mohit1997** [comment]
Just added a new branch with tf 2.0 namely `tf2`. It should work with tensorflow 2. You might have to select the minor version tf2.x accordingly. You can mention that in `install.sh` file. Let me know if there's an error.

**Comment by Yoniming** [comment]
Thank you very much. I solved the problem of environment configuration. Compared with changing the version of tensorflow or keras, it is easier to install CUDA 9.0 in a virtual environment. I will continue to test and learn the code. Thank you again for your patience!

**Comment by mohit1997** [comment]
A lot of people might migrate to tensorflow 2 and hence I thought it would be worth a try. Let me know if you face any issue with DeepZip.
