### ISSUE TITLE
How to use pre-trained models to compress custom files?

### ISSUE THREAD

**Issue by kv304** [mohit1997/DNA_Compression#16]
Hi , I am trying to run the model on a new text file.It is giving out errors like ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

**Comment by mohit1997** [comment]
Please try [no GPU branch](https://github.com/mohit1997/DeepZip/tree/noGPU)? It seems that your system doesn't have a GPU. In case you have a GPU make sure that the command `nvidia-smi` works and you also have CUDA library set up.
