### ISSUE TITLE
the file size issue, facing memory errors on running the algorithm on file size of 100mb.

### ISSUE THREAD

**Issue by kv304** [mohit1997/DNA_Compression#18]
Hi , I was trying to scale up the compression on bigger files and the first file I tried was of size 119 mb. However, there is a memory error on both local(CPU) and colab(GPU) and the algorithm shuts down. Can you please tell me if there are some modifications needed to run it on bigger files?

**Comment by mohit1997** [comment]
I suppose there is no direct way to reduce memory usage. One idea can be changing the loss function such that instead of one-hot vectors, sparse input can be used. That'll reduce memory usage significantly.
