### ISSUE TITLE
Need suggestions on reducing the time for compression/decompression

### ISSUE THREAD

**Issue by kv304** [mohit1997/DNA_Compression#19]
Hi Guys ,

I have significantly reduced the training time for the model and also captured the generalization. However , the algo still takes huge amount of time(approx 2 hours on GPU) to compress/decompress big files(around 300 mb) with the models being pretrained. Any suggestions on how can I reduce this time?

**Comment by mohit1997** [comment]
You can increase the batch size argument in `./src/run_experiments.sh` (line 50 and 51) which will only be helpful depending on GPU compute power and RAM. If you want to further reduce the time you will have to change the model such as a smaller model or use a smaller context length at the cost of reuced compression performance.
