### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by DmitryKuznetsov1** [mohit1997/DNA_Compression#20]
Hey! Our team is solving a similar problem. There is a known problem with the reproducibility of results in the pytorch. It turns out that the compression results differ depending on which machine the code is running on. 
Copying a project to another folder within the same machine results in the code being compiled into a different bytecode with a different order of operations. Using docker and all possible seeds did not solve the problem. 
This does not allow decoding unambiguously. Have you encountered such a problem, and if so, how did you solve it?
![image](https://user-images.githubusercontent.com/33155347/117830408-44822200-b27c-11eb-8ff5-68b2789f7ceb.png)

**Comment by mohit1997** [comment]
Interesting, I haven't tried running compression from a different folder. As far as I remember, the machine issue is very well known but it is not clear why changing the folder should affect the compression. Once the file is read, it shouldn't depend on where the code is being executed. Have you tried running the same on CPU, does that give you reproducible results? 

Sorry, I couldn't be more helpful on this occasion, but intuitively this is a bit surprising. Also are you using multiple GPUs? One possible thing would be to check the outputs after first forward and backward pass to pinpoint the nondeterministic operations. Based on the screenshot, it seems like you are aware of the pytorch implementation but just in case you don't, this might be useful [https://github.com/mohit1997/Dzip-torch](https://github.com/mohit1997/Dzip-torch).
