### ISSUE TITLE
No biLSTM.reconstructed.txt

### ISSUE THREAD

**Issue by ObsisMc** [mohit1997/DNA_Compression#22]
When I run `./run_experiments.sh biLSTM` in noGPU branch, it warns that there is no `biLSTM.reconstructed.txt` in `data/compressed/.../`. How can I solve it?

**Comment by MadL1me** [comment]
@ObsisMc how did you solved that?

**Comment by ObsisMc** [comment]
> @ObsisMc how did you solved that?

Sorry, I forget it.
