### ISSUE TITLE
make: docker: Command not found, [build] Error 127

### ISSUE THREAD

**Issue by mariamorejon** [mohit1997/DNA_Compression#4]
I first tried building on Windows but got a number of errors along with some FileNotFound that looked like the code was searching for a linux-style path.
![linux error](https://user-images.githubusercontent.com/51378135/59448970-c5ec8380-8dcb-11e9-87b9-ced1dd46866f.png)
So I moved to Ubuntu and tried again building there. I am now getting an issue much sooner along in the sample code's process (although this may be because Windows was running nonsense and Linux is actually catching errors).
![new error](https://user-images.githubusercontent.com/51378135/59449133-267bc080-8dcc-11e9-827c-e11e4085485b.png)
I (believe that) I am only able to run tensorflow-cpu because my system does not have a nvidia-make graphics card. Since your master-branch readme suggests that your program will work with either tensorflow CPUor GPU, I first tried to clone and build that. As I mentioned, I am following your readme almost exactly at this point and therefore ran `$ make bash BACKEND=tensorflow GPU=0 DATA=/home/maria/DeepZip`. That raised this Error 127.
I then looked to your closed issues and saw another user, also using CPU and raising this same error.
https://github.com/mohit1997/DeepZip/issues/1
After reading this issue and your solution, I tried to run the make bash line you posted for the noGPU readme with my existing clone, as well as cloning the specific noGPU branch and trying the same on that. Those being specifically, `$ make bash BACKEND=tensorflow DATA=/home/maria/DeepZip`. The same error was raised with each attempt. 
While the error itself gives me almost no information about its cause, it seems as though it might have something to do with trying to run the docker file? I would so appreciate your help with this hangup. Thank you!

**Comment by shubhamchandak94** [comment]
Can you check if docker is installed on your machine?
Regards,
Shubham

**Comment by mariamorejon** [comment]
This does seem to be the issue. As I cannot install docker on Windows 10 Home Edition, it looks like I will not be able to use your algorithm on my machine. Thank you anyway for your help!
