### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by weibo053** [mohit1997/DNA_Compression#5]
I use ubuntu 16.04
I run 
sudo make bash BACKEND=tensorflow GPU=0 DATA=../
It shows the following error information:

Successfully tagged keras:latest
GPU=0 nvidia-docker run -it -v /mnt/4d4a789c-f0f5-49e0-afa1-f94f818ee987/dropbox_files . University)/research/DeepZip:/src/workspace -v ../:/data --env KERAS_BACKEND=tensorflow keras bash
/bin/sh: 1: Syntax error: ")" unexpected
Makefile:19: recipe for target 'bash' failed
make: *** [bash] Error 2

**Comment by kedartatwawadi** [comment]
This seems like a path issue? Bash might not expect the ')' in the path "/mnt/4d4a789c-f0f5-49e0-afa1-f94f818ee987/dropbox_files . University)/research/DeepZip".

Can you try with some other directory?

**Comment by weibo053** [comment]
It works now. Thanks.
