### ISSUE TITLE
Cannot compress xor60

### ISSUE THREAD

**Issue by AnsonHooL** [mohit1997/DNA_Compression#7]
**The log is as follow：**
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (4.32.2)
../data/processed_files/xor60.npy
xor60
../data/processed_files/xor60.param.json
**cmp: ../data/compressed/xor60/.reconstructed.txt: No such file or directory**
2
**cmp: ../data/compressed/xor60/.reconstructed.txt: No such file or directory**
continuing
Starting training ...
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: trainer.py [-h] [-train TRAIN] [-val VAL] [-name NAME]
                  [-model_name MODEL_NAME] [-log_file LOG_FILE]
trainer.py: error: argument -model_name: expected one argument
Starting Compression ...
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: compressor.py [-h] [-model MODEL_WEIGHTS_FILE] [-model_name MODEL_NAME]
                     [-batch_size BATCH_SIZE] [-data SEQUENCE_NPY_FILE]
                     [-data_params PARAMS_FILE] [-output OUTPUT_FILE_PREFIX]
compressor.py: error: argument -model_name: expected one argument
Command exited with non-zero status 2
	Command being timed: "python3 compressor.py -data ../data/processed_files/xor60.npy -data_params ../data/processed_files/xor60.param.json -model ../data/trained_models/xor60/.hdf5 -model_name -output ../data/compressed/xor60/.compressed -batch_size 1000"
	User time (seconds): 3.31
	System time (seconds): 5.59
	Percent of CPU this job got: 695%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.28
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 181948
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 55992
	Voluntary context switches: 164
	Involuntary context switches: 37
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: decompressor.py [-h] [-model MODEL_WEIGHTS_FILE]
                       [-model_name MODEL_NAME] [-batch_size BATCH_SIZE]
                       [-output OUTPUT_FILE_NAME]
                       [-input_file_prefix INPUT_FILE_PREFIX]
decompressor.py: error: argument -model_name: expected one argument
Command exited with non-zero status 2
	Command being timed: "python3 decompressor.py -output ../data/compressed/xor60/.reconstructed.txt -model ../data/trained_models/xor60/.hdf5 -model_name -input_file_prefix ../data/compressed/xor60/.compressed -batch_size 1000"
	User time (seconds): 3.54
	System time (seconds): 5.29
	Percent of CPU this job got: 695%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.27
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 182360
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 56021
	Voluntary context switches: 239
	Involuntary context switches: 66
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2
**cmp: ../data/compressed/xor60/.reconstructed.txt: No such file or directory**
I cannot find the output in the file /compressed/xor60/

**Comment by AnsonHooL** [comment]
../data/compressed/PhiX_quality_truncated**/biGUR.reconstructed.txt: No such file or directory**
Cannot generate this file.How to fix the bug?THX

**Comment by AnsonHooL** [comment]
**trainer.py: error: argument -model_name: expected one argument**

**Comment by kedartatwawadi** [comment]
Can you also post the command which you ran, which gave the issue? 
From the log, it seems like you ran 
`./run_experiments.sh biGUR` 

We do not have a biGUR model. Can you try running 
`./run_experiments.sh biGRU`

**Comment by AnsonHooL** [comment]
> Can you also post the command which you ran, which gave the issue?
> From the log, it seems like you ran
> `./run_experiments.sh biGUR`
> 
> We do not have a biGUR model. Can you try running
> `./run_experiments.sh biGRU`

THX.I recorrected my command.And I ran the command : **sudo ./run_experiments.sh biGRU.**
I use the no-GPU edition as well.
**And the log is as follow:**
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (4.32.2)
../data/processed_files/PhiX_quality_truncated.npy
PhiX_quality_truncated
../data/processed_files/PhiX_quality_truncated.param.json
**cmp: ../data/compressed/PhiX_quality_truncated/biGRU.reconstructed.txt: No such file or directory**
2
**cmp: ../data/compressed/PhiX_quality_truncated/biGRU.reconstructed.txt: No such file or directory**
continuing
Starting training ...
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: trainer.py [-h] [-train TRAIN] [-val VAL] [-name NAME]
                  [-model_name MODEL_NAME] [-log_file LOG_FILE]
**trainer.py: error: unrecognized arguments: -d ../data/processed_files/PhiX_quality_truncated.npy**
Starting Compression ...
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "compressor.py", line 199, in <module>
    main()
  File "compressor.py", line 161, in main
    predict_lstm(X, Y, Y_original, timesteps, batch_size, alphabet_size, args.model_name)
  File "compressor.py", line 65, in predict_lstm
    model = getattr(models, model_name)(bs, timesteps, alphabet_size)
  File "/home/thl/DeepZip-noGPU/src/models.py", line 25, in biGRU
    model.add(Bidirectional(GRU(32, stateful=False, return_sequences=True)))
**NameError: name 'GRU' is not defined**
Command exited with non-zero status 1
	Command being timed: "python3 compressor.py -data ../data/processed_files/PhiX_quality_truncated.npy -data_params ../data/processed_files/PhiX_quality_truncated.param.json -model ../data/trained_models/PhiX_quality_truncated/biGRU.hdf5 -model_name biGRU -output ../data/compressed/PhiX_quality_truncated/biGRU.compressed -batch_size 1000"
	User time (seconds): 40.75
	System time (seconds): 23.95
	Percent of CPU this job got: 113%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:57.00
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 9658736
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 11910090
	Voluntary context switches: 270
	Involuntary context switches: 213927
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "decompressor.py", line 181, in <module>
    main()
  File "decompressor.py", line 150, in main
    f = open(args.input_file_prefix+'.combined','rb')
FileNotFoundError: [Errno 2] **No such file or directory: '../data/compressed/PhiX_quality_truncated/biGRU.compressed.combined'**
Command exited with non-zero status 1
	Command being timed: "python3 decompressor.py -output ../data/compressed/PhiX_quality_truncated/biGRU.reconstructed.txt -model ../data/trained_models/PhiX_quality_truncated/biGRU.hdf5 -model_name biGRU -input_file_prefix ../data/compressed/PhiX_quality_truncated/biGRU.compressed -batch_size 1000"
	User time (seconds): 3.10
	System time (seconds): 5.16
	Percent of CPU this job got: 647%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.27
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 188988
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 57265
	Voluntary context switches: 127
	Involuntary context switches: 505598
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
**cmp: ../data/compressed/PhiX_quality_truncated/biGRU.reconstructed.txt: No such file or directory**

**Comment by mohit1997** [comment]
The `trainer.py` file accepted two arguments for the training sequence and test sequence.  As of now, I have merged both the arguments to a single one as in the master branch. Also, there were imports missing in the models.py file. Please try now.

**Comment by AnsonHooL** [comment]
> The `trainer.py` file accepted two arguments for the training sequence and test sequence. As of now, I have merged both the arguments to a single one as in the master branch. Also, there were imports missing in the models.py file. Please try now.

THX very much.Seems it works now.Would you kindly tell me the compression speed in GPU?
The compress speed is about 2kb/s in my machine without GPU.

**Comment by mohit1997** [comment]
You can take a look at [this](https://chainer.org/general/2017/03/15/Performance-of-LSTM-Using-CuDNN-v5.html) for a comparison. Note that the bottleneck operation in compression, as well as decompression, is a forward pass. Please remember, it will depend upon batch size too.

**Comment by JsBlueCat** [comment]
> > The `trainer.py` file accepted two arguments for the training sequence and test sequence. As of now, I have merged both the arguments to a single one as in the master branch. Also, there were imports missing in the models.py file. Please try now.
> 
> THX very much.Seems it works now.Would you kindly tell me the compression speed in GPU?
> The compress speed is about 2kb/s in my machine without GPU.

how about your compress speed？
